# Workflow name
name: ci

# Triggers the workflow on push or pull request events
on: [push, pull_request]

# Workflow jobs
jobs:
  # Build job
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    # Runs the job on each OS
    runs-on: ${{ matrix.os }}

    # Job steps
    steps:
      # Checkout the repo with submodules
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      # Cache files
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            builddir/
          key: ${{ runner.os }}-meson-${{ hashFiles('**/meson.build', '**/meson_options.txt') }}

      # Setup python
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Setup meson and ninja
      - name: Setup meson and ninja
        run: |
          pip install ninja meson

      # Meson setup [Linux/macOS]
      - name: Meson setup [Linux/macOS]
        if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
        env:
          CC: clang
          CXX: clang++
        run: |
          meson setup --buildtype=release builddir

      # Setup Visual Studio shell [Windows]
      - name: Setup Visual Studio shell [Windows]
        if: ${{ runner.os == 'Windows' }}
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      # Meson setup [Windows]
      - name: Meson setup [Windows]
        if: ${{ runner.os == 'Windows' }}
        env:
          CC: clang-cl
          CXX: clang-cl
        run: |
          meson setup --buildtype=release builddir

      # Meson compile
      - name: Meson compile
        run: |
          ninja -C builddir

      # Meson test
      - name: Run Tests
        run: |
          ninja test -C builddir
